import AppKit
import CryptoKit
import SwiftData

@MainActor
@Observable
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int

    private(set) var isMonitoring = false
    /// Set to true briefly while PasteService writes to pasteboard, so the monitor skips that change.
    var isPasting = false

    static let selfPasteType = NSPasteboard.PasteboardType(Constants.selfPasteUTI)

    private let supportedTypes: [NSPasteboard.PasteboardType] = [
        .string, .html, .rtf, .rtfd, .png, .tiff, .fileURL
    ]

    var onNewClip: ((_ hash: String, _ title: String, _ plainText: String?, _ contentType: ContentType, _ contents: [(String, Data)], _ bundleID: String?, _ appName: String?) -> Void)?

    init() {
        self.lastChangeCount = pasteboard.changeCount
    }

    func start(interval: TimeInterval = Constants.defaultPollingInterval) {
        guard !isMonitoring else { return }
        isMonitoring = true
        lastChangeCount = pasteboard.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.checkPasteboard()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isMonitoring = false
    }

    private func checkPasteboard() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        // Skip while PasteService is actively writing to pasteboard
        if isPasting { return }

        // Skip our own pastes
        if pasteboard.data(forType: Self.selfPasteType) != nil { return }

        // Skip concealed/auto-generated items (password managers, browser extensions)
        if let types = pasteboard.types {
            let typeStrings = types.map(\.rawValue)

            // Standard concealed UTI (used by native password managers)
            if typeStrings.contains(where: { $0.contains("concealed") }) {
                return
            }

            // Auto-generated type (1Password, some extensions)
            if typeStrings.contains(where: { $0.contains("org.nspasteboard.AutoGeneratedType") }) {
                return
            }

            // Vendor-specific UTIs
            if typeStrings.contains(where: { $0.contains("com.agilebits") || $0.contains("com.bitwarden") }) {
                return
            }
        }

        // Skip browser password manager extensions (Bitwarden, 1Password, etc.)
        if UserDefaults.standard.bool(forKey: Constants.UserDefaultsKeys.excludePasswordManagers),
           Self.isPasteFromBrowserPasswordExtension(pasteboard) {
            return
        }

        // Skip excluded apps
        let frontmostBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? ""
        let excludedApps = UserDefaults.standard.stringArray(forKey: Constants.UserDefaultsKeys.excludedApps) ?? []
        if excludedApps.contains(frontmostBundleID) {
            return
        }

        // Skip password managers (enabled by default)
        if UserDefaults.standard.bool(forKey: Constants.UserDefaultsKeys.excludePasswordManagers),
           Constants.passwordManagerBundleIDs.contains(frontmostBundleID) {
            return
        }

        captureClipboard()
    }

    private func captureClipboard() {
        guard let items = pasteboard.pasteboardItems else { return }

        var allContents: [(String, Data)] = []
        var detectedTypes: [NSPasteboard.PasteboardType] = []

        for item in items {
            for type in item.types {
                guard supportedTypes.contains(type),
                      let data = item.data(forType: type) else { continue }
                allContents.append((type.rawValue, data))
                detectedTypes.append(type)
            }
        }

        guard !allContents.isEmpty else { return }

        let hash = computeHash(allContents)
        let plainText = pasteboard.string(forType: .string)
        let title = deriveTitle(plainText: plainText, contents: allContents)
        let contentType = ContentType.primaryType(from: detectedTypes)

        let frontmostApp = NSWorkspace.shared.frontmostApplication
        let bundleID = frontmostApp?.bundleIdentifier
        let appName = frontmostApp?.localizedName

        onNewClip?(hash, title, plainText, contentType, allContents, bundleID, appName)
    }

    // Known password manager browser extension IDs (Chrome Web Store)
    private static let passwordExtensionPrefixes: [String] = [
        // Bitwarden
        "chrome-extension://nngceckbapebfimnlniiiahkandclblb",
        "chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh",
        // 1Password
        "chrome-extension://aeblfdkhhhdcdjpifhhbdiojplfjncoa",
        // LastPass
        "chrome-extension://hdokiejnpimakedhajhdlcegeplioahd",
        // Dashlane
        "chrome-extension://fdjamakpfbbddfjaooikfcpapjhoafdg",
        // NordPass
        "chrome-extension://fooolghllnmhmmndgjiamiiodkpenpbb",
    ]

    private static func isPasteFromBrowserPasswordExtension(_ pasteboard: NSPasteboard) -> Bool {
        guard let items = pasteboard.pasteboardItems else { return false }
        for item in items {
            for type in item.types where type.rawValue.contains("source-url") {
                guard let data = item.data(forType: type),
                      let urlStr = String(data: data, encoding: .utf8) else { continue }
                for prefix in passwordExtensionPrefixes {
                    if urlStr.hasPrefix(prefix) {
                        return true
                    }
                }
            }
        }
        return false
    }

    private func computeHash(_ contents: [(String, Data)]) -> String {
        var hasher = SHA256()
        for (type, data) in contents {
            hasher.update(data: Data(type.utf8))
            hasher.update(data: data)
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }

    private func deriveTitle(plainText: String?, contents: [(String, Data)]) -> String {
        if let text = plainText, !text.isEmpty {
            let firstLine = text.components(separatedBy: .newlines).first ?? text
            return String(firstLine.prefix(Constants.maxTitleLength))
        }

        let typeStrings = contents.map { $0.0 }
        if typeStrings.contains(NSPasteboard.PasteboardType.png.rawValue) ||
           typeStrings.contains(NSPasteboard.PasteboardType.tiff.rawValue) {
            return "Image"
        }
        if typeStrings.contains(NSPasteboard.PasteboardType.fileURL.rawValue) {
            if let urlData = contents.first(where: { $0.0 == NSPasteboard.PasteboardType.fileURL.rawValue })?.1,
               let urlString = String(data: urlData, encoding: .utf8),
               let url = URL(string: urlString) {
                return url.lastPathComponent
            }
            return "File"
        }

        return "BoboMind Item"
    }
}
